# Derived from base16 black-metal — RRethy/base16-nvim: lua/colors/black-metal.lua @ 44fc7a0
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#dd9999"
      - "bold"
    inactiveBorderColor:
      - "#333333"
    searchingActiveBorderColor:
      - "#dd9999"
      - "bold"
    optionsTextColor:
      - "#888888"
    selectedLineBgColor:
      - "#222222"
    cherryPickedCommitFgColor:
      - "#888888"
    cherryPickedCommitBgColor:
      - "#999999"
    markedBaseCommitFgColor:
      - "#000000"
    markedBaseCommitBgColor:
      - "#a06666"
    unstagedChangesColor:
      - "#5f8787"
    defaultFgColor:
      - "#c1c1c1"
